on: push
jobs:
  example1:
    name: create-and-upload-job
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 1 + 1 > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v4
        with:
          name: output-log-file
          path: output.log
  download-file:
    name: Download file
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact        
        uses: actions/download-artifact@v4
        with:
          name: output-log-file
          needs: example1
          
